name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
      - 'hotfix-*'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  static-checks:
    name: Run static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs -sp

      - name: Run Psalm
        run: vendor/bin/psalm --shepherd

  tests:
    name: Test on ${{ matrix.os }} php${{ matrix.php-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        os:
          - ubuntu
          - windows
          - macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pcntl, posix, intl
          coverage: xdebug
          ini-values: error_reporting=E_ALL

      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Normalize ALLURE_MATRIX_ENV
        run: |
          raw_value="${{ matrix.os }}-php-${{ matrix.php-version }}"
          value="$raw_value"
          value="${value//./_}"
          value="${value//\*/x}"
          echo "ALLURE_MATRIX_ENV=${value}" >> "$GITHUB_ENV"
          echo "ALLURE_TEST_DUMP_NAME=allure-results-${value}" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Show Codeception version
        run: |
          echo "Tested against Codeception **v$(
            composer show codeception/codeception --format json | jq -r '.versions[0]'
          )**" >> "$GITHUB_STEP_SUMMARY"
        shell: bash

      - name: Run unit tests
        run: |
          npx -y allure@3 run --config ./allurerc.mjs --rerun 2 --environment="${{ env.ALLURE_MATRIX_ENV }}" --dump="${{ env.ALLURE_TEST_DUMP_NAME }}-unit" -- \
          composer test-unit

      - name: Run samples
        run: |
          npx -y allure@3 run --config ./allurerc.mjs --rerun 2 --environment="${{ env.ALLURE_MATRIX_ENV }}" --dump="${{ env.ALLURE_TEST_DUMP_NAME }}-run-samples" -- \
          composer test-report-generate

      - name: Assert samples
        run: |
          npx -y allure@3 run --config ./allurerc.mjs --rerun 2 --environment="${{ env.ALLURE_MATRIX_ENV }}" --dump="${{ env.ALLURE_TEST_DUMP_NAME }}-assert-samples" -- \
          composer test-report-check

      - name: Upload unit test dump
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ALLURE_TEST_DUMP_NAME }}-unit
          path: ./${{ env.ALLURE_TEST_DUMP_NAME }}-unit.zip
          retention-days: 1

      - name: Upload run samples dump
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ALLURE_TEST_DUMP_NAME }}-run-samples
          path: ./${{ env.ALLURE_TEST_DUMP_NAME }}-run-samples.zip
          retention-days: 1

      - name: Upload assert samples dump
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ALLURE_TEST_DUMP_NAME }}-assert-samples
          path: ./${{ env.ALLURE_TEST_DUMP_NAME }}-assert-samples.zip
          retention-days: 1

  report:
    needs: [tests]
    name: Build Allure report
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read
      pull-requests: write
      checks: write
    env:
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
      ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
      ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Download Allure dumps
        uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          pattern: allure-results-*
          path: ./
          merge-multiple: true

      - name: Generate Allure report
        run: npx -y allure@3 generate --config ./allurerc.mjs --dump="allure-results-*.zip" --output=./out/allure-report

      - name: Post Allure summary
        if: ${{ always() && !cancelled() && contains(fromJSON('["success","failure"]'), needs.tests.result) }}
        uses: allure-framework/allure-action@v0
        with:
          report-directory: ./out/allure-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
