name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
      - 'hotfix-*'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  static-checks:
    name: Run static checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs -sp

      - name: Run Psalm
        run: vendor/bin/psalm --shepherd

  tests:
    name: Test on ${{ matrix.os }} php${{ matrix.php-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        os:
          - ubuntu
          - windows
          - macOS

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pcntl, posix, intl
          coverage: xdebug
          ini-values: error_reporting=E_ALL

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Show Codeception version
        run: |
          echo "Tested against Codeception **v$(
            composer show codeception/codeception --format json | jq -r '.versions[0]'
          )**" >> "$GITHUB_STEP_SUMMARY"
        shell: bash

      - name: Run unit tests tests
        run: composer test-unit

      - name: Run samples
        run: composer test-report-generate

      - name: Assert samples
        run: composer test-report-check
